config setup
    charondebug="ike 2, knl 2, cfg 0, net 0"
    uniqueids=no

conn %default
    keyexchange=ikev2
    authby=secret
    ikelifetime=60m
    lifetime=20m
    margintime=3m
    keyingtries=%forever
    rekey=yes
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart

conn site-to-site
    left=192.168.200.10
    leftid=@site-a
    leftsubnet=192.168.201.0/24
    right=192.168.200.20
    rightid=@site-b
    rightsubnet=192.168.202.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    forceencaps=yes
    auto=start
