networks:
  wan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.64.0.0/24
          gateway: 100.64.0.254
  lan-a:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.64.1.0/24
          gateway: 100.64.1.254
  lan-b:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.64.2.0/24
          gateway: 100.64.2.254

services:
  site-a:
    build:
      context: ./site-a
    container_name: vpn-site-a
    networks:
      wan:
        ipv4_address: 100.64.0.10
      lan-a:
        ipv4_address: 100.64.1.1
    privileged: true
    restart: unless-stopped

  site-b:
    build:
      context: ./site-b
    container_name: vpn-site-b
    networks:
      wan:
        ipv4_address: 100.64.0.20
      lan-b:
        ipv4_address: 100.64.2.1
    privileged: true
    restart: unless-stopped
