networks:
  wan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  lan-a:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
  lan-b:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24

services:
  site-a:
    build:
      context: ./site-a
    container_name: vpn-site-a
    networks:
      wan:
        ipv4_address: 192.168.200.10
      lan-a:
        ipv4_address: 192.168.201.1
    privileged: true
    restart: unless-stopped

  site-b:
    build:
      context: ./site-b
    container_name: vpn-site-b
    networks:
      wan:
        ipv4_address: 192.168.200.20
      lan-b:
        ipv4_address: 192.168.202.1
    privileged: true
    restart: unless-stopped
