config setup
    charondebug="ike 2, knl 2, cfg 0, net 0"
    uniqueids=no

conn %default
    keyexchange=ikev2
    authby=secret
    ikelifetime=60m
    lifetime=20m
    margintime=3m
    keyingtries=%forever
    rekey=yes
    dpddelay=10s
    dpdtimeout=30s
    dpdaction=restart

conn site-to-site
    left=172.20.0.20
    leftid=@site-b
    leftsubnet=10.2.0.0/24
    right=172.20.0.10
    rightid=@site-a
    rightsubnet=10.1.0.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    forceencaps=yes
    auto=add
